#pragma once
#include "map_data.h"
int entity_count;
entity *entities;
entity_geometry *entity_geo;
int texture_count;
texture_data *textures;
int worldspawn_layer_count;
worldspawn_layer *worldspawn_layers;